"use client"

import styles from "../../styles";
import { Navbar , Footer } from "../../components";

const ethicalStandard = () => {
  return (
<>
<Navbar/>   

<section className={`${styles.paddings}`}>
    <Navbar />
      <div className=" mt-16 flex flex-col justify-center items-start ">
        <h2 className=" font-bold text-xl">Ethical Standards</h2>
        <br/>
        <br/>
        
        
        <p>

To be seen as a fair and transparent entity in making the voice of women heard, we follow the undermentioned ethical standards while reporting, talking or supporting any cause on our Websites or our official Social Media Channels as mentioned below</p>
<br/>
<p className=" text-slate-900 font-semibold"> 
1.	Facebook: https://www.facebook.com/TeamHRhelpdesk<br/>
2.	Facebook: https://www.facebook.com/MahilaBol/<br/>
3.	Twitter:https://twitter.com/amar_hrhelpdesk?lang=en<br/>
4.	YouTube: https://www.youtube.com/user/hrhelpdeskdotin<br/>
5.	Instagram: https://www.instagram.com/hrhelpdesk/<br/>
</p>
<br/>
<p>
Should you find any violation in the above mentioned channels from our set ethical standards, please report it to empower@mahilabol.org and we shall look at it at the earliest. In the event of an violation of ethical standards, we may not only remove the post, or mention from our channels, but may also issue a clarification as per our timeframe keeping in due consideration the time taken to complete an unbiased check on the issue raised.
</p>
<br/>
<p>
<span className=" text-slate-900 font-semibold">Data Related Standards</span><br/>
1.	We shall mention data which has been generated by us or our associated agencies and the data can be proven by us or our associated agencies<br/><br/>
2.	We shall present such data which is a result of research or collection done by Government Agencies <span className=" font-semibold">(State or Central)</span> , Universities, Academic Institutions or National and International NGOs working in India<br/><br/>
3.	Data from any other source not covered in the above two points will be put forward only if reasonable checks have been done by us<br/><br/>
4.	All data presented by us shall have the source mentioned with the data</p><br/>
<br/>
<p>
<span className=" text-slate-900 font-semibold">Opinions and Views Related Standards</span> <br/>
1.	As far as possible the purpose of our channel is to provide information and data to readers and viewers to enable them in forming their own views and opinions about a subject.<br/>
2.	Views and opinions presented by individuals on the channel shall be of the individual and shall follow the Promoting Equality Guideline
</p>
<br/>
<br/>
<p>
<span className=" text-slate-900 font-semibold">Promoting Equality Guidelines</span><br/>
1.	The content, views and or opinions presented on our medium shall ensure that<br/>
a.	We do not negatively portray any specific gender (for example, to promote feminism, we do not undermine the importance of men or tarnish an entire group of men)<br/>
b.	We do not publish material which shows any religion in bad light, we shall talk about practices or procedures and not portray any religion in bad light<br/>
c.	Unless not mentioning the religion will take away the entire essence of the publication, we shall refrain from mentioning the religion or those covered in the publication<br/>
d.	We shall foster a healthy representation of political views by political parties or their representatives and discourage publications which are seen as blaming each other in an derogatory manner or are personal attacks at any of the members<br/>
</p>
<br/>
<p>
<span className=" text-slate-900 font-semibold">Reporting Cases or News or Articles</span><br/>
1.	When pointing out or naming individuals or agencies, we recommend talking in specifics rather than generics. Individuals or agencies that are responsible and once documentary proof is seen can only be named in the news or report. We do not name anyone unless we have documentary evidence and we have made a reasonable attempts to reach the party being named to present their side of the story. in the event the other side isn’t responding, such information will be clearly mentioned in the news or report or article</p>


        
      </div>
      
    </section>



<Footer/>
 </>
  );
};

export default ethicalStandard;
